### ISSUE TITLE
Website — Missing link in footer

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/waku-objects-website#19]
In the footer please make "wakuplay.im" a link to https://www.wakuplay.im/
<img width="322" alt="Screenshot 2023-09-20 at 9 05 13" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/46993354/e4db07a8-a1e0-49fa-afdd-f3108a14f1e1">

**Comment by sugarpusher** [comment]
@david-gauquelin 
Question: https://www.wakuplay.im/ is the domain where this website will be (is) hosted, so this would effectively link to itself. Is that your intention?
Thanks!

**Comment by david-gauquelin** [comment]
Yes, this would be the case only for the main page, this is needed for all the subpages to be able to go back to the main page

**Comment by sugarpusher** [comment]
@david-gauquelin sounds good, thanks!
