### ISSUE TITLE
Remove extra line at the bottom of the Waku Chat page

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/waku-objects-website#74]
Remove the line and space at the end of the page 
<img width="1081" alt="Screenshot 2023-10-02 at 9 16 20" src="https://github.com/logos-innovation-lab/waku-objects-website/assets/46993354/f493e2ca-f497-4ffd-9206-4e67eb6f2a92">
https://www.wakuplay.im/waku-chat

**Comment by vojtechsimetka** [comment]
Fixed in 593fee9b453d7148a59e21350832b03f14ffc08c
