### ISSUE TITLE
Intro text style on design guidelines page

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/waku-objects-website#97]
Please let's use a consistent style with the other subpages, the first sentence should be using the h2 style and a smaller paragraph below (see attached screenshot)

<img width="1071" alt="Screenshot 2023-10-04 at 9 06 24" src="https://github.com/logos-innovation-lab/waku-objects-website/assets/46993354/23ae13b6-54e0-4202-a6d8-fa2d75bd5f2f">

**Comment by vojtechsimetka** [comment]
fixed in #100
